root = insert(None, 50)
# insert(root, 20)
# insert(root, 53)
# insert(root, 11)
# insert(root, 22)
# insert(root, 52)
# insert(root, 78)
# print("Height of the binary tree is:")
# print(height(root))